.\" stardict.1 - A Cross-Platform and international dictionary
.\" Copyright (C) 2020  Hu Zheng
.TH stardict 1 "28 Nov 2020"
.SH NAME
StarDict \- A Cross-Platform and international dictionary written in Gtk.
.SH SYNOPSIS
.B stardict
.sp
or select
.B StarDict
from the
.B Utility
submenu of the Applications menu.
.SH DESCRIPTION
.B StarDict
is a Cross-Platform and international dictionary written in Gtk.
It has powerful features such as "Glob-style pattern matching," "Scan selection word," "Fuzzy query," etc.

For full documentation, see the
.B StarDict
GNOME Help Documentation.
.SH OPTIONS
.TP 8
.B \-h
do not show splash screen
.SH AUTHOR
.B StarDict 1.31
(using Motif/LessTif) was originally written by Ma Su'an <msa@wri.com.cn> in 1999.

.B StarDict 1.33+
(enhancement) was written by Opera Wang <wangvisual@sohu.com> in 2002.

.B StarDict 2.0.0
was written by Hu Zheng <huzheng001@gmail.com>.

This manual page was written by Hu Zheng
<huzheng001@gmail.com>.

.SH SEE ALSO
.BR gnome-dictionary (1),
.BR http://stardict-4.sourceforge.net
